---
- hosts: es_master_nodes
  roles:
    - role: elastic.elasticsearch
      become: True
      es_instance_name: "node1"
      es_heap_size: "1g"
      es_config: {
        cluster.name: "gr2-cluster",
        discovery.zen.ping.unicast.hosts: "192.168.56.21:9300,192.168.56.22:9300,192.168.56.23:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: false,
        node.master: true,
        bootstrap.memory_lock: false
      }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
