- hosts: grafana-servers
  tasks:
  - name: Create Grafana user
    user:
      name: grafana
      shell: /usr/sbin/nologin
      state: present
  - name: "create config dir"
    file:
      path: "/etc/grafana"
      state: directory
      mode: "0700"
  - name: "create sqllite dir"
    file:
      path: "/var/lib/grafana"
      state: directory
      mode: "0700"
  - name: "Create Grafana config"
    template:
      src: grafana.ini.j2
      dest: /etc/grafana/grafana.ini
  - name: Start Grafana Container
    docker_container:
      name: grafana
      image: grafana/grafana
      published_ports:
      - "3000:3000"
      volumes:
      - "/var/lib/grafana:/var/lib/grafana"
      - "/etc/grafana:/etc/grafana"
      env:
        GF_SECURITY_ADMIN_PASSWORD: secret
      restart_policy: unless-stopped
      restart: True
