- hosts: server1
  become: True
  tasks:
  - name: Install docker-py
    pip:
      name: docker-py
  - name: start hashi-ui container
  # This container is started with host network mode
  # it is therefore directly accessible on the host interface / port
  # this means here, port 3000
    docker_container:
      name: nomad-ui
      image: jippi/hashi-ui
      network_mode: host
      recreate: True
      restart_policy: always
      volumes:
      - "/etc/vault/ssl:/etc/vault/ssl:ro"
      - "/etc/nomad/ssl:/etc/nomad/ssl:ro"
      env:
        # TODO should be https://nomad.service.consul:4646
        NOMAD_ADDR: https://192.168.56.21:4646
        NOMAD_CACERT: /etc/nomad/ssl/ca.pem
        NOMAD_ENABLE: 1
        CONSUL_ENABLE: 1
        CONSUL_ADDR: "{{ansible_hostname}}:8500"
        CONSUL_ACL_TOKEN: "CH4NG3M3CH4NG3M3CH4NG3M3CH4NG3M3"
  - name: start vault-ui container
    docker_container:
      name: vault-ui
      image: djenriquez/vault-ui
      recreate: True
      restart_policy: always
      ports:
      - "8000:8000"
      env:
        VAULT_URL_DEFAULT: https://active.vault.service.consul:8200
        CUSTOM_CA_CERT: "{{lookup('file','~/pki/ca.pem')}}"
